# Generated by Django 4.1.5 on 2023-01-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_service_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Order',
        ),
    ]
